Repository paritytech/js-libs, pull requests merged in 2019-01, with the labels that each got.

#79 Add postRaw$ method to send raw (already signed) transactions
  packages/light.js/src/index.ts
  packages/light.js/src/rpc/other/post.ts
  packages/light.js/src/rpc/rpc.spec.ts
  packages/light.js/src/rpc/rpc.ts
Labels: package:light.js

#88 Add chainId$
  packages/api/src/rpc/eth/eth.js
  packages/light.js/src/index.ts
  packages/light.js/src/rpc/eth.ts
  packages/light.js/src/utils/testHelpers/mockApi.ts
Labels: package:light.js

#91 WIP: Relates to #81. Update to Electron v4.1.0
  README.md
  package.json
  packages/abi/package.json
  packages/api/package.json
  packages/contracts/package.json
  packages/electron/package.json
  packages/light.js-react/package.json
  packages/light.js/package.json
  yarn.lock
Labels: please review

#97 Publish docs to gh-pages branch of this repo
  scripts/update-docs.sh
Labels: documentation

#99 Use travis deploy to push to gh-pages
  .gitignore
  .travis.yml
  scripts/update-docs.sh
Labels: internal

#100 Generate gh-pages correctly
  .gitignore
  .travis.yml
  scripts/update-docs.sh
Labels: internal

#101 Fix README links
  README.md
Labels: documentation

#93 Rewrite post$ to take a password and not use signer
  packages/api/src/rpc/personal/personal.js
  packages/light.js/docs/guides/tutorial4-send-a-transaction.md
  packages/light.js/docs/guides/tutorial5-work-with-contracts.md
  packages/light.js/src/rpc/other/makeContract.ts
  packages/light.js/src/rpc/other/post.ts
  packages/light.js/src/rpc/rpc.spec.ts
  packages/light.js/src/types.ts
  scripts/lerna-publish.sh
Labels: breaking, package:light.js
